### ISSUE TITLE
Base plate generated by "Generate Plate Instead" generates an incomplete model

### ISSUE THREAD

**Issue by JosephCW** [rianadon/dactyl-configurator#1]
When generating a base plate via the "Generate Plate Instead" option, the .stl file output is not entirely filled in. This happens when using  the default settings.

![image](https://user-images.githubusercontent.com/4164889/224559401-373bd2fb-57e0-4033-af73-92db8b89f1b2.png)

**Comment by rianadon** [comment]
Oh huh this is new for me. Thanks for finding this! I'll take a look.

**Comment by rianadon** [comment]
It looks like all the way back to the original Dactyl Manuform, this is how generating the plates worked. Tom Short (tshort)'s repo has dxfs of each of the plates, so I assume he somehow loaded the STL files into a program that allowed him to export dxfs and fill in the middle.
This process does not sound ideal at all...

I'm planning V2 of this tool (see #4), so this will probably be something I address there.

**Comment by JosephCW** [comment]
Thanks for taking a look into this! I just built a crkbd dactyl based on some files I found on thingiverse but I have a friend who wants me to build a manuform for him and this tool would be perfect since he would be able to customize it too his liking before sending the .stl files my way to print. Looking forward to future updates of this tool :).

**Comment by rianadon** [comment]
I have a lot planned for V2 so it'll probably be several months until I improve the reliability of models on the site.

Is it possible to for you to import the plates into Inkscape/Illustrator/some vector graphics software and clean up the edges? I could also try to write up a guide on this if you're having trouble. It will be faster for me to do that than write the code to do it :)

**Comment by JosephCW** [comment]
I ended up importing it into fusion 360 to get the base plate cleaned up. I have not printed yet but the model itself looks good so far. Thanks again!
<img width="449" alt="image" src="https://user-images.githubusercontent.com/4164889/227239123-314a4440-4c5f-4eff-8263-22e3f447c242.png">

**Comment by rianadon** [comment]
Sorry I just saw this. Wow what a classy keyboard!

I love the choice of transparent filament. That's what I used for mine too :)
