### ISSUE TITLE
Custom Thumb Key uses wrong values when using 5 keys

### ISSUE THREAD

**Issue by willdhorn** [rianadon/dactyl-configurator#5]
When trying to customize the positions of a 5-key thumb cluster, the Middle Left fields do not affect the model preview, and the key that's supposed to be controlled by them is impossible to configure. Instead, that key appears to be configured with the Bottom Right fields, however, these are dimmed out when using 5 keys (which is very helpful and something this configurator does right by hiding irrelevant inputs, with the exception that its hiding the wrong fields) 

It is possible to work around this, though, by setting the thumb cluster to 6 keys, editing the Bottom Right values, and changing the cluster size back to 6.

Thanks for all the work you put into making this configuator work as well as it does! It's leagues above every other dactyl generator I've tried (and there's a lot of them lol). Even this issue, which has a workaround, isn't something that's easy or even feasible with other tools, so kudos to you on making it work at all.

**Comment by willdhorn** [comment]
I just realized the dimmed out fields are still editable, so there's no need to change the thumb cluster size at all! I'll leave the issue open as it's still a visual bug, but I'm able to configure everything just fine without having to use a workaround.

**Comment by rianadon** [comment]
Thanks so much for the detailed writeup! This made it very easy to fix.
