### ISSUE TITLE
Adjusting thumb cluster angle

### ISSUE THREAD

**Issue by bemyak** [rianadon/dactyl-configurator#6]
Hi!

Thanks for an amazing tool!
Is there a way to adjust the thumb cluster tilting angle (i.e., make it more vertical)? I couldn't find this setting, sorry.

**Comment by rianadon** [comment]
There's no way to adjust the tilting angle at once, but you can click the "Custom Thumb Cluster" box and change the positions and angles of each thumb key.

To get the whole thumb cluster to tilt, you'll have to adjust every key. I haven't thought of any better ways to going about this that would be easy to implement.
